<?php
use \TwentyTwoEstore\Libs;

/* $view \TwentyTwoEstore\Libs\View */

echo '<main>';

	if (!empty($view->balances) && is_array($view->balances)){
		$firstBalance = $view->balances[0];
		$lastBalance = $view->balances[count($view->balances) - 1];

		echo '<section id="investment-history">';
			printf('<h3>%s</h3>', 'Total balance history');
			echo '<div id="investment-graph">';
				foreach ($view->balances as $balance){
					drawBalanceBar($balance);
				}
			echo '</div>';
			echo '<div id="investment-info">';
				drawBalanceInfo('Start balance', $firstBalance);
				drawBalanceInfo('End balance', $lastBalance);
			echo '</div>';
		echo '</section>';
	}
echo '</main>';

function drawBalanceBar (Libs\Investor\BoundaryBalance $balance)
{
	$total = $balance->countTotal()->round(0)->toFloat();
	$width = $total * 0.00003;

	printf('<div class="bar" style="width:%dpx"></div>', $width);
}

function drawBalanceInfo ($title, Libs\Investor\BoundaryBalance $balance)
{
	echo '<hr />';
	printf('<h3>%s</h3>', $title);
	printf('<div class="info date-time"><span class="title">%s</span><span class="value">%s</span></div>', 'Date', strftime("%x", $balance->dateTime()->getTimestamp()));
	printf('<div class="info total"><span class="title">%s</span><span class="value">%.2f [pln]</span></div>', 'Total value', $balance->countTotal()->round(0)->toFloat());
}
