<?php
/* $view \TwentyTwoEstore\Libs\View */
?>
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title><?= $view->title() ?> | 24eStore</title>
<!-- 	<link rel="stylesheet" href="/css/bootstrap.css" /> -->
<!-- 	<link rel="stylesheet" href="/css/site.css" /> -->
	<style>
		#investment-graph .bar{
			height: 1px;
			background-color: blue;
		}
		#investment-info>.info>*:first-child{
			width: 10rem;
			display: inline-block;
		}
	</style>
</head>
<body>
<?php
	printf('<h3>%s</h3>', $view->title());
	include $view->fileName();
?>
</body>
</html>
